apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-frontend
  template:
    metadata:
      labels:
        app: gitops-frontend
    spec:
      containers:
      - name: gitops-frontend
        image: samhitha708/gitops-frontend:v1
        ports:
        - containerPort: 80
