apiVersion: v1
kind: Service
metadata:
  name: gitops-frontend
spec:
  type: NodePort
  selector:
    app: gitops-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
