name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Verify Cluster Access
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/        
