name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "KUBECONFIG=${HOME}/.kube/config" >> $GITHUB_ENV

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Ensure Minikube is Running
        run: minikube status

      - name: Debug Minikube
        run: ls -l ~/.minikube/profiles/minikube/

      - name: Check Kubernetes Context
        run: kubectl config view

      - name: Verify Kubernetes Nodes
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/   
